try to use day to predict volume, but keep getting low model score and same predicted values.

In [78]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sn
import datetime
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

plt.style.use('ggplot')


In [79]:
FILE1 = "csv_file\Apple.csv"
FILE2 = "csv_file\Microsoft.csv"
df_apple = pd.read_csv(FILE1)
df_microsoft = pd.read_csv(FILE2)
df_apple = df_apple[df_apple["Date"].str.contains("2020") == False]
df_microsoft = df_microsoft[df_microsoft["Date"].str.contains("2020") == False]
df_apple['Date'] = pd.to_datetime(df_apple.Date, format='%Y-%m-%d')
df_apple.index = df_apple['Date']

df_microsoft['Date'] = pd.to_datetime(df_microsoft.Date, format='%Y-%m-%d')
df_microsoft.index = df_microsoft['Date']

In [80]:
print(df_microsoft.describe())

              Open         High          Low        Close    Adj Close  \
count  8922.000000  8922.000000  8922.000000  8922.000000  8922.000000   
mean     39.405219    39.813412    38.982464    39.412798    34.235384   
std      59.241808    59.807334    58.622170    59.252423    59.453134   
min       0.088542     0.092014     0.088542     0.090278     0.056745   
25%       3.894531     3.945313     3.856445     3.894531     2.447927   
50%      26.670000    26.940001    26.365001    26.650000    18.612948   
75%      37.577501    37.867500    37.197501    37.525937    27.645862   
max     344.619995   349.670013   342.200012   343.109985   341.606354   

             Volume  
count  8.922000e+03  
mean   5.905367e+07  
std    3.864768e+07  
min    2.304000e+06  
25%    3.495510e+07  
50%    5.226045e+07  
75%    7.294255e+07  
max    1.031789e+09  


In [81]:
df_reg_apple = df_apple.copy().loc[:, ['Adj Close', 'Volume']]
df_reg_apple = df_reg_apple['2005-1-1':'2022-8-1'] # wont change the result if change to future date like 2022-9-1
df_reg_apple = df_reg_apple.iloc[:,[1]].reset_index(drop=True)
y_apple_volume = df_reg_apple.values
x_apple_volume = df_reg_apple.index.values.reshape(-1, 1)

x_apple_train, x_apple_test, y_apple_train, y_apple_test = train_test_split(x_apple_volume,y_apple_volume,
                                                                            test_size=0.01,
                                                                            random_state=16,
                                                                            shuffle=True)
                                                                            

In [82]:
print(y_apple_volume)
print(x_apple_volume)

[[ 691992000]
 [1096810400]
 [ 680433600]
 ...
 [  81378700]
 [ 101689200]
 [  67829400]]
[[   0]
 [   1]
 [   2]
 ...
 [4169]
 [4170]
 [4171]]


In [83]:
modelSVR_apple = SVR().fit(x_apple_train, y_apple_train)
modelRFR_apple = RandomForestRegressor().fit(x_apple_train, y_apple_train)
modelABR_apple = AdaBoostRegressor().fit(x_apple_train, y_apple_train)
modelGBR_apple = GradientBoostingRegressor().fit(x_apple_train, y_apple_train)
modelLR_apple = LinearRegression(n_jobs=-1).fit(x_apple_train, y_apple_train)
modelDTR_apple = DecisionTreeRegressor().fit(x_apple_train, y_apple_train)
modelKNR_apple = KNeighborsRegressor(n_neighbors=3).fit(x_apple_train, y_apple_train)      

print('SVR:', modelSVR_apple.score(x_apple_test, y_apple_test))
print('RandomForestRegressor:', modelRFR_apple.score(x_apple_test, y_apple_test))
print('AdaBoostRegressor:', modelKNR_apple.score(x_apple_test, y_apple_test))
print('GradientBoostingRegressor:', modelGBR_apple.score(x_apple_test, y_apple_test))
print('LinearRegression:', modelLR_apple.score(x_apple_test, y_apple_test))
print('DecisionTreeRegressor:', modelDTR_apple.score(x_apple_test, y_apple_test))
print('KNeighborsRegressor:', modelKNR_apple.score(x_apple_test, y_apple_test))

c:\Users\ormosia5\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ormosia5\AppData\Local\Temp\ipykernel_49892\3404906299.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  modelRFR_apple = RandomForestRegressor().fit(x_apple_train, y_apple_train)
c:\Users\ormosia5\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\ormosia5\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\ensemble\_gb.py:570

SVR: -0.018656708488146823
RandomForestRegressor: 0.8508628387738572
AdaBoostRegressor: 0.8420767286546216
GradientBoostingRegressor: 0.8089135122600883
LinearRegression: 0.5913007121351908
DecisionTreeRegressor: 0.8193472326061778
KNeighborsRegressor: 0.8420767286546216


In [84]:
df_reg_microsoft = df_microsoft.copy().loc[:, ['Adj Close', 'Volume']]
df_reg_microsoft = df_reg_microsoft['2005-1-1':'2022-8-1']
df_reg_microsoft = df_reg_microsoft.iloc[:,[1]].reset_index(drop=True)

y_microsoft_volume = df_reg_microsoft.values

x_microsoft_volume = df_reg_microsoft.index.values.reshape(-1, 1)

x_microsoft_train, x_microsoft_test, y_microsoft_train, y_microsoft_test = train_test_split(x_microsoft_volume,y_microsoft_volume,
                                                                            test_size=0.01,
                                                                            random_state=15,
                                                                            shuffle=True)
                                                                       

In [85]:
modelSVR_microsoft = SVR().fit(x_microsoft_train, y_microsoft_train)
modelRFR_microsoft = RandomForestRegressor().fit(x_microsoft_train, y_microsoft_train)
modelABR_microsoft = AdaBoostRegressor().fit(x_microsoft_train, y_microsoft_train)
modelGBR_microsoft = GradientBoostingRegressor().fit(x_microsoft_train, y_microsoft_train)
modelLR_microsoft = LinearRegression(n_jobs=-1).fit(x_microsoft_train, y_microsoft_train)
modelDTR_microsoft = DecisionTreeRegressor().fit(x_microsoft_train, y_microsoft_train)
modelKNR_microsoft = KNeighborsRegressor(n_neighbors=3).fit(x_microsoft_train, y_microsoft_train)      

print('SVR:', modelSVR_microsoft.score(x_microsoft_test, y_microsoft_test))
print('RandomForestRegressor:', modelRFR_microsoft.score(x_microsoft_test, y_microsoft_test))
print('AdaBoostRegressor:', modelKNR_microsoft.score(x_microsoft_test, y_microsoft_test))
print('GradientBoostingRegressor:', modelGBR_microsoft.score(x_microsoft_test, y_microsoft_test))
print('LinearRegression:', modelLR_microsoft.score(x_microsoft_test, y_microsoft_test))
print('DecisionTreeRegressor:', modelDTR_microsoft.score(x_microsoft_test, y_microsoft_test))
print('KNeighborsRegressor:', modelKNR_microsoft.score(x_microsoft_test, y_microsoft_test))

c:\Users\ormosia5\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ormosia5\AppData\Local\Temp\ipykernel_49892\3102763711.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  modelRFR_microsoft = RandomForestRegressor().fit(x_microsoft_train, y_microsoft_train)
c:\Users\ormosia5\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\ormosia5\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\ensembl

SVR: -0.021702466832923095
RandomForestRegressor: 0.6039254304311367
AdaBoostRegressor: 0.589512985873782
GradientBoostingRegressor: 0.3755183736230445
LinearRegression: 0.3861038901097392
DecisionTreeRegressor: 0.6076650183061737
KNeighborsRegressor: 0.589512985873782


In [86]:
print(df_reg_apple.index.values.reshape(-1, 1)) # get total days
print(df_reg_microsoft.index.values.reshape(-1, 1))

[[   0]
 [   1]
 [   2]
 ...
 [4169]
 [4170]
 [4171]]
[[   0]
 [   1]
 [   2]
 ...
 [4169]
 [4170]
 [4171]]


In [87]:
# predict future 30 day volume from the day 4126 
day = 30 
x_pred = [[j+4162 for i in range(1)] for j in range(day)]

y_pred = modelRFR_apple.predict(x_pred)
y_pred

array([80259175., 69425749., 64971578., 64941274., 57205437., 56571166.,
       74205681., 80580682., 91862234., 74254331., 74254331., 74254331.,
       74254331., 74254331., 74254331., 74254331., 74254331., 74254331.,
       74254331., 74254331., 74254331., 74254331., 74254331., 74254331.,
       74254331., 74254331., 74254331., 74254331., 74254331., 74254331.])

In [89]:
day = 30
x_pred = [[j+4162 for i in range(1)] for j in range(day)]

y_pred = modelRFR_microsoft.predict(x_pred)
y_pred

array([23861522., 23248553., 22532548., 22146395., 22969844., 34673838.,
       41496631., 36100547., 31843973., 25595003., 25595003., 25595003.,
       25595003., 25595003., 25595003., 25595003., 25595003., 25595003.,
       25595003., 25595003., 25595003., 25595003., 25595003., 25595003.,
       25595003., 25595003., 25595003., 25595003., 25595003., 25595003.])